# Top-level configuration
name = "my-sms-forwarder"
main = "src/index.ts"
compatibility_date = "2024-05-17" # Or your desired compatibility date, check your project's generation

# Bind a KV Namespace. Use 'wrangler kv:namespace create <NAMESPACE_NAME>' to create one.
kv_namespaces = [
  { binding = "SMS_DB_KV", id = "<your_kv_namespace_id_placeholder>", preview_id = "<your_kv_namespace_preview_id_placeholder>" } # Add preview_id for local dev
]

# Environment variables for your worker
# You can add new variables here, or add secrets using 'wrangler secret put <KEY>'
# Note: Secrets are not visible in this file after 'wrangler secret put'.
[vars]
CLOUDFLARE_TURNSTILE_SECRET_KEY = "<your_turnstile_secret_key_placeholder>"
WEBHOOK_SECRET = "<generate_a_strong_secret_for_webhook>"
JWT_SECRET = "<generate_a_strong_secret_for_jwt_signing>"

# [[migrations]]
# tag = "v1" # A unique identifier for this migration
# new_classes = ["DurableObjectExample"] # Array of new Durable Object class names 